@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/react.puml

title Container diagram van het Triptop reis systeem

Person(reiziger, "Reiziger", "[persoon]\nIngelogde gebruiker van Triptop", $sprite="users")
Person(reisagent, "Reisagent", "[persoon]\nHelpt reizigers met risicovermindering", $sprite="users")

System_Boundary(triptop, "Triptop reis systeem") {
    Container(frontend, "Frontend", "React", "Interface voor gebruikers om d.m.v. van bouwstenen een reis samen te stellen.", $sprite="react")
    Container(backend, "Backend", "Java, Spring Boot", "Online platform voor reisplanning", $sprite="java")
    ContainerDb(database, "Database", "SQL", "Slaat reisgegevens en boekingen op", $sprite="msql_server")
}

System_Ext(airbnbapi, "Airbnb API", "Accommodaties via airbnb.nl")
System_Ext(SixtApi, "Sixt API", "Autoverhuur")
System_Ext(identityProviderAPI, "Identity Provider API", "Authenticatie en autorisatie")
System_Ext(NsApi, "NS API", "API voor treininformatie en tickets")

Rel(reiziger, frontend, "Stelt reis samen, boekt, past aan of annuleert", "HTTPS")
Rel(reisagent, frontend, "Biedt advies en ondersteuning", "HTTPS")
Rel(frontend, backend, "Stuurt API-verzoeken")
Rel(backend, database, "Leest van en schrijft naar")
Rel(backend, airbnbapi, "Boekt verblijfplaatsen", "HTTPS")
Rel(backend, SixtApi, "Verhuurt auto's",  "HTTPS")
Rel(backend, identityProviderAPI, "Beheert authenticatie en autorisatie",  "HTTPS")
Rel(backend, NsApi, "Koopt treintickets",  "HTTPS")


SHOW_FLOATING_LEGEND()
Lay_Distance(LEGEND(), identityProviderAPI, 2)
@enduml