@startuml
!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

LAYOUT_WITH_LEGEND()

title Context diagram voor het Triptop reis systeem

Person(reiziger, "Reiziger", "Stelt zijn reis zelf samen")
Person(reisagent, "Reisagent", "Biedt ondersteuning en advies")

System_Boundary(triptop, "Triptop Systeem") {
    Container(frontend, "Frontend", "React", "Biedt een gebruikersinterface voor klanten")
    Container(backend, "Backend", "Java", "Online platform voor reisplanning")
    Container(bookings, "Booking Service", "Java", "Plaatst boekingen van de gebruiker op Booking.com")
    Container(login, "Login Service", "Java", "Handelt het inloggen van de gebruiker af")
    ContainerDb(database, "Database", "SQL", "Slaat reisgegevens en boekingen op")
}

System_Ext(bookingAPI, "Booking API", "Verblijfsaccommodaties via Booking.com")
System_Ext(MapsAPI, "Maps API", "Routeplanning en navigatie")
System_Ext(identityProviderAPI, "Identity Provider API", "Authenticatie en autorisatie")

Rel(reiziger, frontend, "Stelt reis samen, boekt, past aan of annuleert")
Rel(reisagent, frontend, "Biedt advies en ondersteuning")
Rel(frontend, backend, "Maakt API-verzoeken")
Rel(backend, database, "Leest/schrijft reisgegevens en boekingen")
Rel(bookings, bookingAPI, "Boekt verblijfplaatsen")
Rel(backend, MapsAPI, "Plant routes en navigatie")
Rel(login, identityProviderAPI, "Beheert authenticatie en autorisatie")
Rel(backend, bookings, "Plaatst boekingen via")
Rel(backend, login, "Autoriseert gebruikers via")

@enduml