@startuml
title Adapter Pattern - Hotels Ophalen
skinparam linetype ortho

interface HotelApiAdapter {
   + fetchHotels(): String
}

class BookingService {
    + fetchBookingHotels(): String
}

class TripadvisorService {
    + fetchTripadvisorHotels(): String
}

class BookingApiAdapter {
   + fetchHotels(): String
}

class TripadvisorApiAdapter {
    + fetchHotels(): String
}

class BookingController {
   + getAvailableHotelsBooking(): String
}

class TripadvisorController{
   + getAvailableHotelsTripadvisor(): String
}

HotelApiAdapter <|.. BookingApiAdapter
HotelApiAdapter <|.. TripadvisorApiAdapter

BookingApiAdapter --> BookingService : -bookingService
TripadvisorApiAdapter --> TripadvisorService : -tripadvisorService

BookingController --> BookingService : -bookingService
TripadvisorController --> TripadvisorService : -tripadvisorService

note left of BookingApiAdapter
    return bookingService.fetchBookingHotels()
end note


note right of TripadvisorApiAdapter
        return tripadvisorService.fetchTripadvisorHotels()
end note

@enduml