@startuml
!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

LAYOUT_WITH_LEGEND()

title Component diagram voor TravelExpensePro

Container(travelexpensepro, "TravelExpensePro", "container: React, Spring Boot", "Geeft alle functionaliteiten omtrent reizen naar de gebruiker via de browser")
ContainerDb(database, "Database", "SQL", "Slaat reisgegevens en boekingen op")

System_Boundary(travelexpense, "TravelExpensePro Systeem") {
Container(authorizationcontroller, "AuthorizationController", "Component: Spring MVC Rest Controller", "Regelt in en uitloggen voor gebruikers")
Container(expensecontroller, "ExpenseController", "Component: Spring MVC Rest Controller","Regelt toevoegen en verwijderen van reiskosten, gekoppeld aan een specifieke gebruiker")

Container(authorizationservice, "AuthorizationService", "Component: Spring Service", Creeert sessie na succesvolle log-in")
Container(expenseservice, "ExpenseService", "Component: Spring Service","Regel toevoegen en verwijderen van reiskosten, gekoppeld aan een specifieke gebruiker")

Container(sessionrepository, "SessionRepository", "Component: Spring Repository","Biedt een gebruikersinterface voor klanten")
Container(userrepository, "UserRepository", "Component: Spring Repository","Biedt een gebruikersinterface voor klanten")
Container(expenserepository, "ExpenseRepository", "Component: Spring Repository","Biedt een gebruikersinterface voor klanten")
}

Rel(travelexpensepro, authorizationcontroller, "Maakt API calls naar")
Rel(travelexpensepro, expensecontroller, "Maakt API calls naar")
Rel(authorizationcontroller, authorizationservice, "gebruikt")
Rel(expensecontroller, authorizationservice, "gebruikt")
Rel(expensecontroller, expenseservice, "gebruikt")
Rel(authorizationservice, sessionrepository, "gebruikt")
Rel(authorizationservice, userrepository, "gebruikt")
Rel(expenseservice, expenserepository, "gebruikt")

Rel(sessionrepository, database, "Leest van en schrijft naar")
Rel(userrepository, database, "Leest van en schrijft naar")
Rel(expenserepository, database, "Leest van en schrijft naar")

@enduml