@startuml
set separator none
title Dynamisch Container Diagram - Inloggen
!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/java.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/react.puml

Component(login, "Login", "React Component", $sprite="react")
Component(authorisationServiceFacade, "AuthorisationServiceFacade", "Java Spring Boot", $sprite="java")
Container_Ext(identityProvider, "Identity Provider API", "Extern systeem", "Authenticatie en autorisatie")

Rel_R(login, authorisationServiceFacade, "1. Stuurt gegevens naar Identity Provider", "HTTP/JSON")
Rel_R(authorisationServiceFacade, identityProvider, "2. authenticatie via Identity Provider", "HTTP/JSON")
Rel_R(identityProvider, authorisationServiceFacade, "3. Identity Provider bevestigt succesvolle authenticatie", "HTTP/JSON")
Rel_R(authorisationServiceFacade, login, "4. Provider stuurt token terug", "HTTP/JSON")

SHOW_LEGEND(true)
@enduml
