@startuml
!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

LAYOUT_WITH_LEGEND()

title Container diagram van Triptop

Person(reiziger, "Reiziger\n[persoon]", "Klant van Triptop")
Person(reisagent, "Reisagent\n[persoon]", "Medewerker van Triptop")

System_Boundary(triptop, "Triptop Systeem") {
    Container(frontend, "Frontend", "React","Biedt een gebruikersinterface voor klanten")
    Container(backend, "Backend", "Java", "Online platform voor reisplanning")
    ContainerDb(database, "Database", "SQL", "Slaat reisgegevens en boekingen op")
}

System_Ext(bookingAPI, "Booking API", "Verblijfsaccommodaties via Booking.com")
System_Ext(MapsAPI, "Google Maps API", "navigeert en toont de locatie van boekingen")
System_Ext(identityProviderAPI, "Identity Provider API", "Authenticatie en autorisatie")
System_Ext(tripAdvisor, "Trip advisor API", "Reviews van boekingen")

Rel(reiziger, frontend, "Stelt reis samen, boekt, past aan of annuleert")
Rel(reisagent, frontend, "Biedt advies en ondersteuning")
Rel(frontend, backend, "Maakt API-verzoeken", "HTTP/JSON")
Rel(backend, database, "Leest/schrijft reisgegevens en boekingen", "TCP/IP/SQL")
Rel(backend, bookingAPI, "Boekt verblijfplaatsen", "HTTP/JSON")
Rel(frontend, MapsAPI, "Toont locatie via", "HTTP/JSON")
Rel(backend, identityProviderAPI, "Beheert authenticatie en autorisatie", "HTTP/JSON")
Rel(backend, tripAdvisor, "Haalt reviews op via", "HTTP/JSON")

@enduml