@startuml
!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/react.puml
!include FONTAWESOME/users.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
LAYOUT_WITH_LEGEND()

title Component diagram voor TravelExpensePro

Container(travelexpensepro, "TravelExpensePro", "container: React, Spring Boot", "Geeft alle functionaliteiten omtrent reizen naar de gebruiker via de browser", $sprite="react")
ContainerDb(database, "Database", "SQL", "Slaat reisgegevens en boekingen op", $sprite="msql_server")

System_Boundary(travelexpense, "TravelExpensePro Systeem") {
Component(authorizationcontroller, "AuthorizationController", "Component: Spring MVC Rest Controller", "Regelt in en uitloggen voor gebruikers")
Component(expensecontroller, "ExpenseController", "Component: Spring MVC Rest Controller","Regelt toevoegen en verwijderen van reiskosten, gekoppeld aan een specifieke gebruiker")

Component(authorizationservice, "AuthorizationService", "Component: Spring Service", "Creeert sessie na succesvolle log-in")
Component(expenseservice, "ExpenseService", "Component: Spring Service","Regelt toevoegen en verwijderen van reiskosten, gekoppeld aan een specifieke gebruiker")

Component(sessionrepository, "SessionRepository", "Component: Spring Repository","Beheert sessies van ingelogde gebruikers")
Component(userrepository, "UserRepository", "Component: Spring Repository","Beheert gebruikersgegevens")
Component(expenserepository, "ExpenseRepository", "Component: Spring Repository","Beheert reiskosten en koppeling aan gebruikers")
}

Rel(travelexpensepro, authorizationcontroller, "maakt API calls naar")
Rel(travelexpensepro, expensecontroller, "maakt API calls naar")
Rel(authorizationcontroller, authorizationservice, "gebruikt")
Rel(expensecontroller, authorizationservice, "gebruikt")
Rel(expensecontroller, expenseservice, "gebruikt")
Rel(authorizationservice, sessionrepository, "gebruikt")
Rel(authorizationservice, userrepository, "gebruikt")
Rel(expenseservice, expenserepository, "gebruikt")

Rel(sessionrepository, database, "leest van en schrijft naar", "SQL")
Rel(userrepository, database, "leest van en schrijft naar", "SQL")
Rel(expenserepository, database, "leest van en schrijft naar", "SQL")

@enduml